# Glossary of Terms {#glossary .tabset .tabset-fade .tabset-pills}

## Classic Centers {-}

1. [Incenter](http://mathworld.wolfram.com/incenter.html), $X_1$
1. [Barycenter / Centroid](http://mathworld.wolfram.com/TriangleCentroid.html), $X_2$
1. [Circumcenter](http://mathworld.wolfram.com/Circumcenter.html), $X_3$
1. [Orthocenter](http://mathworld.wolfram.com/Orthocenter.html), $X_4$
1. [Nine-Point Center](http://mathworld.wolfram.com/Nine-PointCenter.html), $X_5$
1. [Symmedian / Lemoine Point](http://mathworld.wolfram.com/SymmedianPoint.html), $X_6$
1. [Gergonne Point](http://mathworld.wolfram.com/SymmedianPoint.html), $X_7$
1. [Nagel Point](http://mathworld.wolfram.com/NagelPoint.html), $X_8$
1. [Mittenpunkt](http://mathworld.wolfram.com/Mittenpunkt.html), $X_9$
1. [Spieker Center](http://mathworld.wolfram.com/Mittenpunkt.html), $X_{10}$
1. [Feuerbach Point](http://mathworld.wolfram.com/FeuerbachPoint.html), $X_{11}$
  
## Notable Circles {-}
  
1. [Circumcircle](http://mathworld.wolfram.com/Circumcircle.html)
1. [Circumradius](http://mathworld.wolfram.com/Circumradius.html)
1. [Cosine aka. 2nd Lemoine](http://mathworld.wolfram.com/CosineCircle.html)
1. [Incircle](http://mathworld.wolfram.com/Incircle.html)
1. [Inradius](http://mathworld.wolfram.com/Inradius.html)
1. [1st Lemoine](http://mathworld.wolfram.com/FirstLemoineCircle.html)
1. [Nine-Point aka. Euler](http://mathworld.wolfram.com/Nine-PointCircle.html)
1. [Taylor](http://mathworld.wolfram.com/TaylorCircle.html)
1. [Tucker](http://mathworld.wolfram.com/TuckerCircles.html)

## Derived Triangles {-}

1. [Anticomplementary](http://mathworld.wolfram.com/AnticomplementaryTriangle.html)
1. [Cevian](http://mathworld.wolfram.com/CevianTriangle.html)
1. [Contact](http://mathworld.wolfram.com/ContactTriangle.html)
1. [Equilateral Cevian](http://mathworld.wolfram.com/EquilateralCevianTrianglePoint.html)
1. [Euler](http://mathworld.wolfram.com/EulerTriangle.html)
1. [Excentral](http://mathworld.wolfram.com/ExcentralTriangle.html)
1. [Extouch](http://mathworld.wolfram.com/ExtouchTriangle.html)
1. [Feuerbach](http://mathworld.wolfram.com/FeuerbachTriangle.html)
1. [Incentral](http://mathworld.wolfram.com/IncentralTriangle.html)
1. [Malfatti](http://mathworld.wolfram.com/MalfattiTriangle.html)
1. [Medial](http://mathworld.wolfram.com/MedialTriangle.html)
1. [Orthic](http://mathworld.wolfram.com/OrthicTriangle.html)
1. [Pedal](http://mathworld.wolfram.com/PedalTriangle.html)
1. [Symmedial](http://mathworld.wolfram.com/SymmedialTriangle.html)
1. [Tangential](http://mathworld.wolfram.com/TangentialTriangle.html)

## Equilateral Triangles {-}

1. [Circumnormal](http://mathworld.wolfram.com/CircumnormalTriangle.html)
1. [Circumtangential](http://mathworld.wolfram.com/CircumtangentialTriangle.html)
1. [Morley](http://mathworld.wolfram.com/FirstMorleyTriangle.html)
1. [Napoleon](http://mathworld.wolfram.com/OuterNapoleonTriangle.html)
1. [Stammler](http://mathworld.wolfram.com/StammlerTriangle.html)

## Triangle Centers {-}

1. [Barycentric Coordinates](http://mathworld.wolfram.com/BarycentricCoordinates.html)
1. [Kimberling Center](http://mathworld.wolfram.com/KimberlingCenter.html)
1. [Triangular Center](http://mathworld.wolfram.com/TriangleCenter.html)
1. [Trilinear Coordinates](http://mathworld.wolfram.com/TrilinearCoordinates.html)

## Inconics & Circumconics {-}

1. [Brianchon Point](http://mathworld.wolfram.com/BrianchonPoint.html)
1. [Circumconic](http://mathworld.wolfram.com/Circumconic.html)
1. [Circumellipse](http://mathworld.wolfram.com/Circumellipse.html)
1. [Feuerbach Hyperbola](http://mathworld.wolfram.com/FeuerbachHyperbola.html)
1. [Inellipse](http://mathworld.wolfram.com/Inellipse.html)
1. [Jerabek Hyperbola](http://mathworld.wolfram.com/JerabekHyperbola.html)
1. [Mandart's Inellipse](http://mathworld.wolfram.com/MandartInellipse.html)
1. [McBeath Circumconic](http://mathworld.wolfram.com/MacBeathCircumconic.html)
1. [Orthic Inconic](http://mathworld.wolfram.com/OrthicInconic.html)
1. [Steiner Circumellipse](http://mathworld.wolfram.com/ExtouchTriangle.html)
1. [Yff Parabola](http://mathworld.wolfram.com/YffParabola.html)

## Conics {-}

1. [Conic Section](http://mathworld.wolfram.com/ConicSection.html)
1. [Pascal's Theorem](http://mathworld.wolfram.com/PascalsTheorem.html)
1. [Polar](http://mathworld.wolfram.com/Polar.html)

## General {-}

1. [Anticomplement](http://mathworld.wolfram.com/Anticomplement.html)
1. [Antiorthic Axis](http://mathworld.wolfram.com/AntiorthicAxis.html)
1. [Billiards](http://mathworld.wolfram.com/Billiards.html)
1. [Brocard Angle](http://mathworld.wolfram.com/BrocardAngle.html)
1. [Cosine Hexagon](http://mathworld.wolfram.com/CosineCircle.html)
1. [Feuerbach's Theorem](http://mathworld.wolfram.com/FeuerbachsTheorem.html)
1. [Gergonne Line](http://mathworld.wolfram.com/GergonneLine.html)
1. [Inversion Pole](http://mathworld.wolfram.com/InversionPole.html)
1. [Isogonal Conjugate](http://mathworld.wolfram.com/IsogonalConjugate.html)
1. [Isotomic Conjugate](http://mathworld.wolfram.com/IsogotomicConjugate.html)
1. [Pascal Lines](http://mathworld.wolfram.com/PascalLines.html)
1. [Perspector](http://mathworld.wolfram.com/Perspector.html)
1. [Perspectrix](http://mathworld.wolfram.com/Perspectrix.html)
1. [Trilinear Pole](http://mathworld.wolfram.com/TrilinearPole.html)
1. [Trilinear Polar](http://mathworld.wolfram.com/TrilinearPolar.html)